development:
  adapter: postgresql
  encoding: unicode
  database: sample_app_development
  pool: 5
  username: chrisjacob
  password:
  host: localhost
  min_messages: WARNING

test:
  adapter: postgresql
  encoding: unicode
  database: sample_app_test
  pool: 5
  username: chrisjacob
  password:
  host: localhost
  min_messages: WARNING